services:
  mysql8:
    image: mysql:8
    restart: unless-stopped
    environment:
      # 方法一：设置时区为上海
      - TZ=Asia/Shanghai
      # - SET_CONTAINER_TIMEZONE=true # 方法二： 设置时区为上海
      # - CONTAINER_TIMEZONE=Asia/Shanghai # 方法二： 设置时区为上海
      # mysql启动时自动创建数据库
      - MYSQL_DATABASE=chen17
      # 设置root账户密码
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - mysql8_data:/data/db
    # 和本机共享网络，设置了host模式的网络，就不需要暴露端口了，因为是和主机共享了
    # network_mode: 'host'
    # 设置了host模式的网络，就不需要暴露端口了，因为是和主机共享了
    ports:
      - "3306:3306"
    command: [
        "mysqld",
        # 设置字符编码
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]

  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: 882b91e6ae14fbc4889a49b7bd67b32a034d5fdcad4d4f040abbadbba0cfc86f
    depends_on:
      db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami_db_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  meilisearch:
    image: getmeili/meilisearch:v1.8
    restart: unless-stopped
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=QlyZuSEAvEOcG4OavcZdK+M0tmHvRFRoCXzOsLh4iK263y68HDb0Yj/Dkq3v/FOC
      # - MEILI_ENV=production
      # 开发环境可以进自带的页面查看数据，生产环境不可以
      - MEILI_ENV=development
    volumes:
      - meilisearch_db:/data

volumes:
  mysql8_data:
  umami_db_data:
  meilisearch_db:
